### ISSUE TITLE
Generated Title is not title-y enough

### ISSUE THREAD

**Issue by catastrophe-brandon** [infinitewarp/programmer-title-generator#1]
See screencap here:
https://www.dropbox.com/s/o9x0aa7jlq4rljh/Screenshot%202017-06-05%2019.47.22.png?dl=0

**Comment by infinitewarp** [comment]
https://www.youtube.com/watch?v=IueMdK9I4Qg

If my back-of-the-envelope math is right, you have a 1/16 chance of getting a single-term title (e.g. "Engineer") but a 1/144 chance of specifically getting "Developer" as your title. Lucky you! 🎉
